openapi: 3.0.3
info:
  title: "mobile-order-system"
  version: "1.0.0"
paths:
  /login:
    post:
      summary: "Login"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '401':
          description: "Unauthorized"
  /setting/tables:
    put:
      summary: "update table count"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - new_table_count
              properties:
                new_table_count:
                  type: integer
      responses:
        '200':
          description: "OK"
        '401':
          description: "Unauthorized"
        '422':
          description: "Unprocessable Entity"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Cannot set table count higher than 20"
  /setting/items:
    post:
      summary: "add new item"
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              required:
                - name
                - price
                - image
                - cost_price
                - tax_rate_id
              properties:
                name:
                  type: string
                price:
                  type: integer
                image:
                  type: string
                  format: binary
                cost_price:
                  type: integer
                tax_rate_id:
                  type: integer
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        '401':
          description: "Unauthorized"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ファイルのアップロードに失敗しました"
  /setting/items/{id}:
    patch:
      summary: "update item"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                price:
                  type: integer
                cost_price:
                  type: integer
                tax_rate_id:
                  type: integer
      responses:
        '200':
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Item"
        '401':
          description: "Unauthorized"
        '404':
          description: "Not Found"
        '500':
          description: "Internal Server Error"
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "ファイルのアップロードに失敗しました"

components:
  schemas:
    Token:
      type: object
      properties:
        token:
          type: string
    Item:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        price:
          type: integer
        s3_key:
          type: string
        cost_price:
          type: integer
        tax_rate_id:
          type: integer
    Error:
      type: object
      properties:
        message:
          type: string  
          
