name: PHP-CS-Fixer

on:
  pull_request:

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.3.11

      - name: Install Dependencies
        run: composer update -q --no-ansi --no-interaction --no-scripts --prefer-dist --working-dir=backend/tools/php-cs-fixer

      - name: PHP-CS-Fixer Version
        run: ./backend/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --version

      - name: PHP-CS-Fixer Run
        run: ./backend/tools/php-cs-fixer/vendor/bin/php-cs-fixer fix --config=./backend/.php-cs-fixer.dist.php --verbose
      
      - name: Commit changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add .
          git commit -m "Apply PHP-CS-Fixer"
          git push origin HEAD:refs/heads/$GITHUB_HEAD_REF